#!/bin/zsh
set -e

echo "====================== Build Web3 node client for macOS ======================"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "[1/4] Check Python"
python3 --version

echo "[2/4] Install runtime dependencies"
mkdir -p build
cat > build/client-runtime-requirements.txt <<'EOF'
requests
pywebview
EOF
python3 -m pip install -r build/client-runtime-requirements.txt

echo "[2.5/4] Check PyInstaller"
if ! python3 -m PyInstaller --version >/dev/null 2>&1; then
    echo "PyInstaller is required for building the macOS client."
    echo "Installing PyInstaller from default pip index..."
    if ! python3 -m pip install PyInstaller; then
        echo "Retry installing PyInstaller from Tsinghua mirror..."
        python3 -m pip install PyInstaller -i https://pypi.tuna.tsinghua.edu.cn/simple
    fi
fi

if ! python3 -m PyInstaller --version >/dev/null 2>&1; then
    echo "PyInstaller is not installed for the current Python interpreter."
    echo "If you are using a very new Python version, install Python 3.12 or 3.13 and run this script again."
    echo "You can also install manually:"
    echo "python3 -m pip install PyInstaller -i https://pypi.tuna.tsinghua.edu.cn/simple"
    exit 1
fi

echo "[3/4] Build macOS client with PyInstaller"
if [ -f node.icns ]; then
    python3 -m PyInstaller --clean -F -w --icon node.icns --name web3-node client/main.py
else
    python3 -m PyInstaller --clean -F -w --name web3-node client/main.py
fi

echo "[4/4] Copy sidecar config files"
mkdir -p dist
if [ ! -f dist/node_config.json ]; then
    cp client/node_config.example.json dist/node_config.json
fi
if [ -f .env ] && [ ! -f dist/.env ]; then
    cp .env dist/.env
fi

echo "====================== Build complete ======================"
echo "Executable: dist/web3-node"
echo "App bundle: dist/web3-node.app (when generated by PyInstaller)"
echo "Config: dist/node_config.json"
